run:
  name: baseline

io:
  base_dir: /lustre/storeB/users/ansju8054/roms-ting/testmix
  input_dir: /lustre/storeB/users/ansju8054/roms-ting/testmix/runs/baseline/input
  output_dir: /lustre/storeB/users/ansju8054/roms-ting/testmix/runs/baseline/output
  roms_dir: /lustre/storeB/users/ansju8054/roms-ting/roms

files:
  grd: testmix_grd.nc
  ini: testmix_ini.nc
  bry: testmix_bry.nc

grid:
  Lm: 38
  Mm: 48
  N: 40
  H0: 150.0     # uniform depth (m)
  DX: 800.0     # grid spacing xi (m)
  DY: 800.0     # grid spacing eta (m)

GLS:            # gen closure
  P: 2.0
  M: 1.0
  N: -0.67
  Kmin: 1.0
  Pmin: 1.0
  CMU0: 0.527
  C1: 1.0
  C2: 1.22
  C3M: 0.05
  C3P : 1.0
  SIGK: 0.8
  SIGP: 1.07

vertical:
  Vtransform: 2
  Vstretching: 5
  THETA_S: 5.0
  THETA_B: 4.0
  HC: 100.0

time_stepping:
  NTIMES: 15120  # 60480 for month, 15120 for week, 2160 for day

phys:
  F0: 1.263e-4  # Coriolis (s^-1)

structure:
  str_a: 0.001            
  depth_zero_below: 1.0e9 # set to a large number to keep full column non-zero
  eta_limits: [12, 22]    # define where str_a is non-zero
  xi_limits: [14, 24]
  CD: 0.63
  c4: 1.4

boundary:
  bry_time_seconds: 0.0

  # Boundary values (per edge)
  zeta:
    north: 0
    south: 0
    east: 0.03
    west: -0.03

  zeta_slope:
    north: 1.931e-6
    south: 1.931e-6
    east: 0
    west: 0

  ubar:
    north: 0.0
    south: 0.0
    east: 0.0
    west: 0.0

  vbar:
    north: 0.15
    south: 0.15
    east: 0.15
    west: 0.15

initial:
  ocean_time_seconds: 0.0   # time stamp for the IC file

  # Barotropic (2D) velocities (constant fields)
  ubar_constant: 0.0
  vbar_constant: 0.15

  # 3D velocities (constant through the column)
  u_constant: 0.0
  v_constant: 0.15

  # Free-surface slope west to east
  zeta_slope: 1.931e-6                   # corresponds to 0.15 m/s geostrophic velocity

  # Temperature profile: T = temp_T0 + temp_dT * exp(z/ temp_scale)
  temp_T0: 14.0
  temp_dT: 8.0
  temp_scale: 50.0

  # Salinity (constant)
  salt_S0: 35.0